version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: API/Dockerfile
    ports:
       - "8080:8080"  
        
     
  #DESKTOP-77B8NCD:
  #  image: mcr.microsoft.com/mssql/server
  #  environment:
  #    SA_PASSWORD: 1234567789
  #    ACCEPT_EULA: Y
  #  ports:
  #    - "1433:1433"
 

      